version: "3.7"
services:
  keycloak:
    image: jboss/keycloak:15.0.2
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
    ports:
      - ${KEYCLOAK_PORT}:8080
